name: Docker Image CI

on: [push]	
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:	
  release:	
    runs-on: ubuntu-16.04	
    steps:	
    - uses: actions/checkout@v1	
    - name: Docker linting	
      run: docker run --rm -i hadolint/hadolint < Dockerfile	
    - name: Heroku login	
      uses: actions/heroku@master
      with:	
        args: container:login	
    - name: Heroku push	
      uses: actions/heroku@master	
      with:	
        args: container:push -a dummy-container web
    - name: Heroku release	
      uses: actions/heroku@master	
      with:	
        args: container:release -a dummy-container web